# NOTE(Jake): 2018-07-25
#
#
# For a less stale example of a SilverStripe 4 .travis.yml file, I suggest seeing
# what UserForms is doing:
# - https://github.com/silverstripe/silverstripe-userforms/blob/master/.travis.yml
#

# Additional SilverStripe 3.X info
# See: https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

php:
  # Silverstripe 4
  - 5.6

env:
  matrix:
    # Silverstripe 4
    #
    - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    #
    # Silverstripe 4
    #
    - php: 7.0
      env:
        - RECIPE_VERSION=1.1.x-dev
        - PHPCS_TEST=1
        - DB=PGSQL
        - PHPUNIT_TEST=1
    - php: 7.1
      env:
        - RECIPE_VERSION=4.2.x-dev
        - DB=MYSQL
        - PDO=1
        - PHPUNIT_TEST=1
    - php: 7.2
      env:
        - RECIPE_VERSION=4.x-dev
        - DB=MYSQL
        - PDO=1
        - PHPUNIT_TEST=1

before_script:
  #
  # Silverstripe 4
  #
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.0.x-dev; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  #
  # Silverstripe 4
  #
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ ; fi